let n1 = Number(prompt('Digite o primeiro número:'))
let n2 = Number(prompt('Digite o segundo número:'))
alert(`A soma é ${n1 + n2}`)
alert(`A subtração é ${n1 - n2}`)
alert(`A multiplicação é ${n1 * n2}`)
alert(`A divisão é ${n1 / n2}`)
alert(`O resto da divisão é ${n1 % n2}`)